Reintroduce apply to round modal and banner
gitcoinco/grants-hub pull request #273
Opened 2022-08-24 19:45 UTC by DanieleSalatti

2022-08-26 12:11 UTC, gravityblast requested changes
I noticed we set `roundToApply` to null in `Show` and to a value in `Apply`. shouldn't it be the opposite? So that when you actually go to the application form we set it to null and we don't show the modal anymore. I tried it in local and I always see the modal if I go to the dashboard

2022-08-26 12:11 UTC, gravityblast commented on client/src/components/grants/List.tsx
> +              );
here you can use the `roundPath` function here passing `roundPath(chainId, roundId)`

2022-08-26 12:11 UTC, gravityblast commented on client/src/components/grants/List.tsx
> +            }
to avoid all these checks  can we maybe use `JSON.parse` and `JSON.stringify` to set and get items in the local storage hook?

2022-08-26 12:11 UTC, gravityblast commented on client/src/components/grants/List.tsx
> +          );
here you can use the roundPath function too

2022-08-26 19:25 UTC, codenamejason commented on client/src/components/grants/List.tsx
> +            }
I know we had to do this bc localStorage is saving the boolean as a string, so this make sense. We could save like:
```
{ toggleModal: true }
```
and use the JSON methods you mentioned.

2022-08-30 18:05 UTC, codenamejason commented
Closing this for PR #282

2022-08-30 18:05 UTC, closed without merging